### ISSUE TITLE
Support for https protocol. 

### ISSUE THREAD

**Issue by flowck** [flowck/Jaysun#3]
```
_http_client.js:55
throw new Error('Protocol "' + protocol + '" not supported. ' +
^

Error: Protocol "https:" not supported. Expected "http:"
at new ClientRequest (_http_client.js:55:11)
at Object.exports.request (http.js:31:10)
at getJSONeasily (/home/flowck/Documents/open_source/getjson/getjsoneasily.js:29:17)
at Object.<anonymous> (/home/flowck/Documents/open_source/getjson/example.js:3:1)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.runMain (module.js:604:10)`

```

**Comment by flowck** [comment]
Fixed.
